### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by dmiralles2009** [google/supl-client#1]
The code fails to compile properly because some of the dependencies it needs are non-existing anymore under the suggested package. This is happening when the code tries to import `com.google.location.suplclient.supl.Ephemeris.IonosphericModelProto;`  from withing `SuplLppClientHelper.java`

**Comment by coleHafner** [comment]
+1 

I just ran into the same issue. I'm was really hoping to get this built. Has anyone been able to get around this error?

**Comment by dmiralles2009** [comment]
@coleHafner check my forked version that I think I fixed this a while ago. I should try to get a PR done

**Comment by coleHafner** [comment]
@dmiralles2009 I still get the same error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/colehafner/Sites/__nordic/supl-client-2/target/generated-sources/protobuf/java/com/google/location/suplclient/supl/Ephemeris.java:[50,9] cannot find symbol
  symbol:   class UnusedPrivateParameter
  location: class com.google.location.suplclient.supl.Ephemeris.GpsTimeProto
[ERROR] /Users/colehafner/Sites/__nordic/supl-client-2/target/generated-sources/protobuf/java/com/google/location/suplclient/supl/Ephemeris.java:[650,9] cannot find symbol
  symbol:   class UnusedPrivateParameter
  location: class com.google.location.suplclient.supl.Ephemeris.IonosphericModelProto
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.285 s
[INFO] Finished at: 2019-10-10T15:20:59-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project SuplClient: Compilation failure: Compilation failure:
[ERROR] /Users/colehafner/Sites/__nordic/supl-client-2/target/generated-sources/protobuf/java/com/google/location/suplclient/supl/Ephemeris.java:[50,9] cannot find symbol
[ERROR]   symbol:   class UnusedPrivateParameter
[ERROR]   location: class com.google.location.suplclient.supl.Ephemeris.GpsTimeProto
[ERROR] /Users/colehafner/Sites/__nordic/supl-client-2/target/generated-sources/protobuf/java/com/google/location/suplclient/supl/Ephemeris.java:[650,9] cannot find symbol
[ERROR]   symbol:   class UnusedPrivateParameter
[ERROR]   location: class com.google.location.suplclient.supl.Ephemeris.IonosphericModelProto
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I'm attempting to compile with maven:
```bash
cd <project dir>
mvn initialize
mvn compile
```

**Comment by coleHafner** [comment]
Ah, nevermind. `src/main/ephemeris.proto` had a reference to the `IonosphericModelProto` still. I commented that out and it now builds.

**Comment by lc6chang** [comment]
I'm using MacOS and got the same issue. A simple workaround is to manually complie the proto object file (mentioned in `README.md`). 
e.g.
```bash
$ cd supl-client
$ protoc --java_out=src/main/java src/main/proto/ephemeris.proto
```
